/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideLeft: typeof import('./src/components/layout/aside-left/aside-left.vue')['default']
    AsideLeftContent: typeof import('./src/components/layout/aside-left/aside-left-content.vue')['default']
    AsideRight: typeof import('./src/components/layout/aside-right/aside-right.vue')['default']
    AsideRightContent: typeof import('./src/components/layout/aside-right/aside-right-content.vue')['default']
    BellPopoverTaskList: typeof import('./src/components/layout/main-header/bell-popover-task-list.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    Header: typeof import('./src/components/layout/header.vue')['default']
    MainFooter: typeof import('./src/components/layout/main-footer.vue')['default']
    MainHeader: typeof import('./src/components/layout/main-header/main-header.vue')['default']
    MenuButton: typeof import('./src/components/layout/main-header/menu-button.vue')['default']
    PopoverTitle: typeof import('./src/components/layout/main-header/popover-title.vue')['default']
    ProfileAvatar: typeof import('./src/components/layout/main-header/profile-avatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/layout/main-header/search-input.vue')['default']
    TaskCard: typeof import('./src/components/shared/task-card.vue')['default']
    TaskModal: typeof import('./src/components/shared/task-modal.vue')['default']
    Title: typeof import('./src/components/layout/main-header/title.vue')['default']
  }
}
